name: Deploy FastAPI to AWS

on:
  push:
    branches: [ "main" ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest   
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build, tag, and push to Lambda
      run: |
        sudo apt-get install python3-pip
        sudo pip install virtualenv 
        virtualenv venv 
        source venv/bin/activate
        pip install fastapi mangum uvicorn
        pip freeze > requirements.txt
        sudo apt-get update
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm
        npm i -g serverless
        serverless config credentials --provider aws --key ${{ env.AWS_ACCESS_KEY_ID }} --secret ${{ env.AWS_SECRET_ACCESS_KEY }}
        serverless plugin install -n serverless-python-requirements
        serverless deploy